nameOverride: ""
fullnameOverride: ""
replicaCount: 1
annotations: {}
podAnnotations: {}
image:
  repository: test
  tag: test
  pullPolicy: ""
env: []
envFrom: []
resources:
  limits:
    cpu: 150m1231
    memory: "412"
  requests:
    cpu: 100m
    memory: 200Mi
volumeMounts: null
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms: []
tolerations: []
ports: []
service:
  ports: []
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
ingress: {}
hpa:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  metrics: []
