replicaCount: 2
image:
  repository: nginx
  tag: "1.16"
env: []
envFrom: []
resources:
  limits:
    cpu: ""
    memory: ""
  requests:
    cpu: ""
    memory: ""
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - regular
tolerations: []
ports:
  name: ""
  containerPort: 0
  protocol: ""
service:
  ports: []
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
ingress: {}
hpa:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  metrics: []
