apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replacemetemplate
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: gitops-data-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: replacemeproject 

  source:
    repoURL: {{ .Values.argocd.spec.source.repoURL }}
    targetRevision: {{ .Values.argocd.spec.source.targetRevision }}
    path: "clusters/{{ .Values.cloudProvider }}-{{ .Values.clusterProjectName }}/services/replacemetemplate"
    helm:
      releaseName: replacemetemplate
      valueFiles:
        - values.yaml

  destination:
    server: {{ .Values.argocd.spec.destination.server }}
    namespace: replacemeproject 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
